### ISSUE TITLE
Flashes when trying to load participant profile

### ISSUE THREAD

**Issue by AllanKoder** [Code-the-Change-YYC/hackathon-management-tool#55]
Occasionally, when I visit the participant profile page. It rapidly redirects between the register and profile page.

https://github.com/Code-the-Change-YYC/hackathon-management-tool/assets/74692833/fc14694a-ee96-4658-884c-2390d61a7825

**Comment by ideen1** [comment]
This is a really common one. I think I found the fix and will push it up soon

**Comment by ideen1** [comment]
@burtonjong  Mentioned he might have a fix too

**Comment by burtonjong** [comment]
It keeps flashing between /login and /participant/profile and these are in the files WithAuthGuard.tsx and PersonalFormFields.tsx

What I am assuming is that since data.completedRegistration is true, it will redirect to /participant/profile
![image](https://github.com/user-attachments/assets/9621d1e5-b8e0-4b31-86ef-e32ee1bd5c52)

And then when it is passed to AuthGuard, it automatically redirects back to /login. Or something similar at least

![image](https://github.com/user-attachments/assets/aad4ab6f-92f2-4794-b175-23c0c412cd86)

It also good to note that once it redirects to the user profile page, the reason that it doesnt load any of the data is because ID is an empty string/null, meaning that the UserContext does not successfully load the users ID. This may be able to be solved using Hub.listen() which I did and then invalidating the queries again everytime an auth event occurs (login, logout, etc.)

**Comment by burtonjong** [comment]
Basically, by using Hub.listen() when the user verifies their account using the email code and the account is created in Cognito, the hub listens on the auth event in the UserContext and then is able to pass the users ID before the user profile is even loaded ensuring that the user profile will load
